web:
 image: nginx:1.7
 ports:
  - '80:80'
  - '443:443'
 volumes:
  - ./:/var/www/html
  - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
 working_dir: /var/www/html
 links:
  - fpm
  - mysql
fpm:
 build: ./docker/
 volumes:
  - ./:/var/www/html
 working_dir: /var/www/html
 links:
  - mysql
mysql:
 image: mysql:5.6
 environment:
  - MYSQL_ROOT_PASSWORD=12345
  - MYSQL_DATABASE=test
  - MYSQL_USER=test
  - MYSQL_PASSWORD=password
 ports:
  - "3306:3306"
 volumes:
  - ./db:/docker-entrypoint-initdb.d

